server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://124.222.35.20:3319/shiro?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ding
    password: dyw20020304
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  main:
    allow-circular-references: true
  redis:
    host: 124.222.35.20
    password: dyw20020304
    port: 6666
    database: 1

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath*:org/dyw/mapper/xml/*.xml
  type-aliases-package: com.dyw.entity

shiro:
  sessionManager:
    sessionIdCookieEnabled: false


