server:
  port: 8080
  servlet:
    context-path: /shiro
spring:
  datasource:
    url: jdbc:mysql://124.222.35.20:3319/shiro?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: dyw20020304
    username: ding
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5       # ?????
      max-active: 20        # ?????
      max-wait: 60000       # ??????
      time-between-eviction-runs-millis: 60000      # ??????
      min-idle: 5           #?????
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8

  redis:
    host: 106.12.167.1
    port: 9999
    password: Include020116
    database: 0
    # ????
  mail:
    host: smtp.qq.com #????? smtp.qq.com
    username: 1842501760@qq.com #??????XXXXXXX@qq.com
    default-encoding: UTF-8 #????
    password: xrggjyvgyhrgbhjd  #????? XXXIX
    port: 25 #??

mybatis-plus:
  type-aliases-package: com.dyw.shirospringboot.entity
  mapper-locations: classpath:com/dyw/shirospringboot/entity/mapper/*/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  level:
#    root: warn